include "application"

queues {
  peon-deployments {
    defaultVisibilityTimeout = 10 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "peon-deployments-dlq"
      maxReceiveCount = 3
    }
  }
  peon-deployments-dlq {}

  peon-tasks {
    defaultVisibilityTimeout = 10 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "peon-tasks-dlq"
      maxReceiveCount = 3
    }
  }
  peon-tasks-dlq {}
}
