import { describe, expect, it } from 'vitest';
import {
  createHostKeyVerifier,
  HostKeyMismatchError,
  normalizeHostKeyFingerprint,
  sha256Fingerprint,
} from '../host-key';
import { fingerprintFromPublicKey } from '../keygen';

// Real ed25519 key generated by OpenSSH. The expected value is what
// `ssh-keygen -lf` printed for it, so this pins us to OpenSSH's own output.
const PUBLIC_KEY_LINE =
  'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMEywvC+UVaq+gdjAq1glZ/emFlIdgMW28UqLj7lniff peon-test';
const KEY_BLOB = Buffer.from(PUBLIC_KEY_LINE.split(' ')[1], 'base64');
const FINGERPRINT = 'SHA256:xgaHZJqeRCRLgfyYleqvphpKFa/cJFqZZ3s0bWVSvDc';
const KEYGEN_LINE = `256 ${FINGERPRINT} peon-test (ED25519)`;

describe('sha256Fingerprint', () => {
  it('matches what ssh-keygen -lf prints for the same key', () => {
    expect(sha256Fingerprint(KEY_BLOB)).toBe(FINGERPRINT);
  });

  it('agrees with the private-key fingerprint helper', () => {
    expect(fingerprintFromPublicKey(PUBLIC_KEY_LINE)).toBe(sha256Fingerprint(KEY_BLOB));
  });
});

describe('normalizeHostKeyFingerprint', () => {
  it('accepts the forms a user is likely to paste', () => {
    expect(normalizeHostKeyFingerprint(FINGERPRINT)).toBe(FINGERPRINT);
    expect(normalizeHostKeyFingerprint(`  ${FINGERPRINT}  `)).toBe(FINGERPRINT);
    expect(normalizeHostKeyFingerprint(KEYGEN_LINE)).toBe(FINGERPRINT);
    // Bare digest, and one that still carries base64 padding.
    expect(normalizeHostKeyFingerprint(FINGERPRINT.slice('SHA256:'.length))).toBe(FINGERPRINT);
    expect(normalizeHostKeyFingerprint(`${FINGERPRINT}=`)).toBe(FINGERPRINT);
  });

  it('rejects anything that is not a SHA256 fingerprint', () => {
    expect(normalizeHostKeyFingerprint('')).toBeNull();
    expect(normalizeHostKeyFingerprint('   ')).toBeNull();
    expect(normalizeHostKeyFingerprint(null)).toBeNull();
    expect(normalizeHostKeyFingerprint(undefined)).toBeNull();
    // MD5 fingerprints are not silently accepted.
    expect(normalizeHostKeyFingerprint('16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48')).toBeNull();
    // Wrong length.
    expect(normalizeHostKeyFingerprint('SHA256:tooshort')).toBeNull();
    expect(normalizeHostKeyFingerprint(`SHA256:${'A'.repeat(44)}`)).toBeNull();
  });
});

describe('createHostKeyVerifier', () => {
  it('accepts and learns the key when nothing is pinned yet', () => {
    const verifier = createHostKeyVerifier({ expected: null });

    expect(verifier.verify(KEY_BLOB)).toBe(true);
    expect(verifier.learned).toBe(FINGERPRINT);
    expect(verifier.mismatch).toBeNull();
  });

  it('accepts a key that matches the pin, in any accepted input form', () => {
    for (const pin of [FINGERPRINT, KEYGEN_LINE, FINGERPRINT.slice('SHA256:'.length)]) {
      const verifier = createHostKeyVerifier({ expected: pin });

      expect(verifier.verify(KEY_BLOB), pin).toBe(true);
      // A pinned key is never re-learned, so it can never be silently replaced.
      expect(verifier.learned, pin).toBeNull();
      expect(verifier.mismatch, pin).toBeNull();
    }
  });

  it('rejects a key that does not match the pin and records both sides', () => {
    const other = `SHA256:${'A'.repeat(43)}`;
    const verifier = createHostKeyVerifier({ expected: other });

    expect(verifier.verify(KEY_BLOB)).toBe(false);
    expect(verifier.learned).toBeNull();
    expect(verifier.mismatch).toEqual({ expected: other, actual: FINGERPRINT });
  });

  it('treats an unparseable pin as "not pinned" rather than as a mismatch', () => {
    // Otherwise a bad stored value would lock the server out with no way back.
    const verifier = createHostKeyVerifier({ expected: 'garbage' });

    expect(verifier.verify(KEY_BLOB)).toBe(true);
    expect(verifier.learned).toBe(FINGERPRINT);
  });
});

describe('HostKeyMismatchError', () => {
  it('names the host and both fingerprints', () => {
    const err = new HostKeyMismatchError('10.0.0.1', {
      expected: FINGERPRINT,
      actual: `SHA256:${'A'.repeat(43)}`,
    });

    expect(err).toBeInstanceOf(Error);
    expect(err.name).toBe('HostKeyMismatchError');
    expect(err.message).toContain('10.0.0.1');
    expect(err.message).toContain(FINGERPRINT);
    expect(err.expected).toBe(FINGERPRINT);
  });
});
